#!/usr/bin/env python

## NOTE: ##
## this setup.py was generated by zero2pypi:
## http://gfxmonk.net/dist/0install/zero2pypi.xml

from setuptools import *
setup(
	packages = find_packages(exclude=['test', 'test.*']),
	version='0.7',
	url='http://gfxmonk.net/dist/0install/mocktest.xml',
	name='mocktest',
	install_requires=['setuptools'],
	description='mocking library for python, inspired by rspec',
	long_description="\n**Note**: This package has been built automatically by\n`zero2pypi <http://gfxmonk.net/dist/0install/zero2pypi.xml>`_.\nIf possible, you should use the zero-install feed instead:\nhttp://gfxmonk.net/dist/0install/mocktest.xml\n\n----------------\n\nmocktest\n********\n... is a powerful and easy-to-use mocking library, inspired by rspec and\nsimilar in some ways to Michael Foord's popular Mock module.\n\nSource / Issues:\nhttp://github.com/gfxmonk/mocktest/tree/master\n\n\nZero install feed:\nhttp://gfxmonk.net/dist/0install/mocktest.xml\n(this is the preferred distribution method)\n\n\nCheese shop entry:\nhttp://pypi.python.org/pypi/mocktest\n\n\nDocumentation / Installation\n----------------------------\nPlease see the full documentation online at:\nhttp://gfxmonk.net/dist/doc/mocktest/doc/\n",
classifiers=[
			"License :: OSI Approved :: BSD License",
			"Programming Language :: Python",
			"Intended Audience :: Developers",
			"Topic :: Software Development :: Libraries :: Python Modules",
			"Topic :: Software Development :: Testing",
			"Programming Language :: Python :: 2",
			"Programming Language :: Python :: 3",
		],
		keywords='test mock expect expectation stub rspec unittest',
		license='GPLv3'
)
